name: RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  run-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

            - name: Install Tailscale (auto-resolves latest version)
        shell: pwsh
        run: |
          Write-Host "Fetching latest Tailscale Windows installer URL..."
          $release = Invoke-RestMethod -Uri "https://pkgs.tailscale.com/api/v1/download?os=windows&arch=amd64" -UseBasicParsing
          $url = $release.url
          Write-Host "Resolved to $url"
          $outfile = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $url -OutFile $outfile -UseBasicParsing
          Write-Host "Installing Tailscale silently..."
          Start-Process "msiexec.exe" -ArgumentList "/i `"$outfile`" /qn" -Wait
          Write-Host "Installation complete."


      - name: Add Tailscale to PATH
        shell: pwsh
        run: |
          $env:Path += ";C:\Program Files\Tailscale"
          Write-Host "PATH updated."

      - name: Start Tailscale
        shell: pwsh
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}" --hostname github-rdp --ssh
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4

      - name: Enable RDP
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'

      - name: Keep Session Alive (heartbeat)
        shell: pwsh
        run: |
          for ($i=0; $i -lt 21600; $i += 60) {
            Write-Host "Session alive for $i seconds..."
            Start-Sleep -Seconds 60
          }
